/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.vixcart.admin.req.mod;

import com.vixcart.admin.hash.Hashing;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Random;

/**
 * @company techvay
 * @author rifaie
 */
public class AddMember {
    private final String at;
    private String admin_id;
    private String type;
    private final String mType;
    private final String name;
    private final String email;
    private final String mobile;
    private String new_member_id;
    private String password;
    private String salt;
    private String passwordToken;

    public AddMember(String at, String mType, String name, String email, String mobile) {
        this.at = at;
        this.mType = mType;
        this.name = name;
        this.email = email;
        this.mobile = mobile;
    }

    public void setAdmin_id(String admin_id) {
        this.admin_id = admin_id;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setNew_member_id(String new_member_id) {
        this.new_member_id = new_member_id;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public void setPasswordToken(String passwordToken) {
        this.passwordToken = passwordToken;
    }

    public String getAt() {
        return at;
    }

    public String getAdmin_id() {
        return admin_id;
    }

    public String getType() {
        return type;
    }

    public String getmType() {
        return mType;
    }

    public String getName() {
        return name;
    }

    public String getEmail() {
        return email;
    }

    public String getMobile() {
        return mobile;
    }

    public String getNew_member_id() {
        return new_member_id;
    }

    public String getPassword() {
        return password;
    }

    public String getSalt() {
        return salt;
    }

    public String getPasswordToken() {
        return passwordToken;
    }
    
    public void setAutoGeneratedValues() throws Exception {
        generatePassword();
        genHash();
    }

    private void generatePassword() throws NoSuchAlgorithmException, InvalidKeySpecException {
        Random ran = new Random();
        int length = ran.nextInt(10) + 30;
        password = new_member_id + admin_id + length;
        salt = Hashing.generateSalt(length);
        password = Hashing.hashPassword(password.toCharArray(), salt.getBytes(), 24000, 256);
    }

    /**
     *
     * @throws NoSuchAlgorithmException
     * @throws UnsupportedEncodingException
     * @throws java.security.spec.InvalidKeySpecException
     */
    public void genHash() throws NoSuchAlgorithmException, UnsupportedEncodingException, InvalidKeySpecException {
        passwordToken = Hashing.genVKey(email + type + password + System.currentTimeMillis());
    }

}

