/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vixcart.admin.req.mod;

import com.vixcart.admin.hash.Hashing;
import java.io.UnsupportedEncodingException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.Random;

/**
 * @company techvay
 * @author rifaie
 */
public class AddUser {

    private final String at;
    private String admin_id;
    private String type;
    private final String name;
    private final String designation;
    private final String address1;
    private final String address2;
    private final String place;
    private final String pin;
    private final String utype;
    private final String uname;
    private final String email;
    private String new_admin_id;
    private String password;
    private String salt;
    private String passwordToken;
    private String userType;

    public AddUser(String at, String designation, String name, String address1, String address2, String place, String pin, String utype, String uname, String email) {
        this.at = at;
        this.name = name;
        this.designation = designation;
        this.address1 = address1;
        this.address2 = address2;
        this.place = place;
        this.pin = pin;
        this.utype = utype;
        this.uname = uname;
        this.email = email;
    }

    public String getUserType() {
        return userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getPasswordToken() {
        return passwordToken;
    }

    public String getNew_admin_id() {
        return new_admin_id;
    }

    public void setNew_admin_id(String new_admin_id) {
        this.new_admin_id = new_admin_id;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getDesignation() {
        return designation;
    }

    public void setAdmin_id(String admin_id) {
        this.admin_id = admin_id;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getAt() {
        return at;
    }

    public String getAdmin_id() {
        return admin_id;
    }

    public String getType() {
        return type;
    }

    public String getName() {
        return name;
    }

    public String getAddress1() {
        return address1;
    }

    public String getAddress2() {
        return address2;
    }

    public String getPlace() {
        return place;
    }

    public String getPin() {
        return pin;
    }

    public String getUtype() {
        return utype;
    }

    public String getUname() {
        return uname;
    }

    public String getEmail() {
        return email;
    }

    public void setAutoGeneratedValues() throws Exception {
        generatePassword();
        genHash();
    }

    private void generatePassword() throws NoSuchAlgorithmException, InvalidKeySpecException {
        Random ran = new Random();
        int length = ran.nextInt(10) + 30;
        password = new_admin_id + admin_id + length;
        salt = Hashing.generateSalt(length);
        password = Hashing.hashPassword(password.toCharArray(), salt.getBytes(), 24000, 256);
    }

    /**
     *
     * @throws NoSuchAlgorithmException
     * @throws UnsupportedEncodingException
     * @throws java.security.spec.InvalidKeySpecException
     */
    public void genHash() throws NoSuchAlgorithmException, UnsupportedEncodingException, InvalidKeySpecException {
        passwordToken = Hashing.genVKey(email + type + password + System.currentTimeMillis());
    }

}
